[build-system]
requires = ["setuptools>=46.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py38']

[tool.ruff]
line-length = 120
extend-ignore = [
    "E402", # Need to move imports to top of files
	"E741", # Need to change logger variable away from l
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "F401", # Need to define __all__ in __init__.py
    "F403", # Need to remove * imports in __init__.py
]
